language: ruby
cache: bundler
before_script:
  - cp config/settings.yml.sample config/settings.yml
script: bundle exec rake test
rvm:
  - 2.1.0
services:
  - redis-server
notifications:
  email: false
